name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment (you can adjust the node-version as needed)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build your project (adjust this if needed, e.g., npm run build)
    - name: Build project
      run: npm run build

    # Step 5: Deploy to Firebase
    - name: Deploy to Firebase
      uses: firebase-tools/action-hosting-deploy@v0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
